/* Autogenerated by JAX-SB Compiler (null)
 * THIS FILE SHOULD NOT BE EDITED */
package org.w3.www._2001.XInclude;

@java.lang.SuppressWarnings("all")
@javax.annotation.Generated(value = "Autogenerated by JAX-SB Compiler (null)", date = "2021-09-05")
public class yAA extends org.jaxsb.runtime.Schema {

  static {
    _$$registerElement(
        org.w3.www._2001.XInclude.yAA.Include.NAME, org.w3.www._2001.XInclude.yAA.Include.class);
    _$$registerSchemaLocation(
        org.w3.www._2001.XInclude.yAA.Include.NAME.getNamespaceURI(),
        org.w3.www._2001.XInclude.yAA.Include.class,
        "org.w3.www._2001.XInclude.xsd");

    _$$registerType(
        org.w3.www._2001.XInclude.yAA.$IncludeType.NAME,
        org.w3.www._2001.XInclude.yAA.$IncludeType.class);
    _$$registerSchemaLocation(
        org.w3.www._2001.XInclude.yAA.$IncludeType.NAME.getNamespaceURI(),
        org.w3.www._2001.XInclude.yAA.$IncludeType.class,
        "org.w3.www._2001.XInclude.xsd");

    _$$registerType(
        org.w3.www._2001.XInclude.yAA.$ParseType.NAME,
        org.w3.www._2001.XInclude.yAA.$ParseType.class);
    _$$registerSchemaLocation(
        org.w3.www._2001.XInclude.yAA.$ParseType.NAME.getNamespaceURI(),
        $ParseType.class,
        "org.w3.www._2001.XInclude.xsd");

    _$$registerElement(
        org.w3.www._2001.XInclude.yAA.Fallback.NAME, org.w3.www._2001.XInclude.yAA.Fallback.class);
    _$$registerSchemaLocation(
        org.w3.www._2001.XInclude.yAA.Fallback.NAME.getNamespaceURI(),
        org.w3.www._2001.XInclude.yAA.Fallback.class,
        "org.w3.www._2001.XInclude.xsd");

    _$$registerType(
        org.w3.www._2001.XInclude.yAA.$FallbackType.NAME,
        org.w3.www._2001.XInclude.yAA.$FallbackType.class);
    _$$registerSchemaLocation(
        org.w3.www._2001.XInclude.yAA.$FallbackType.NAME.getNamespaceURI(),
        org.w3.www._2001.XInclude.yAA.$FallbackType.class,
        "org.w3.www._2001.XInclude.xsd");
  }

  @org.jaxsb.runtime.QName(
      namespaceURI = "http://www.w3.org/2001/XInclude",
      localPart = "include",
      prefix = "xi")
  public static class Include extends org.w3.www._2001.XInclude.yAA.$IncludeType
      implements org.jaxsb.runtime.ComplexType, org.jaxsb.runtime.Element {
    private static final javax.xml.namespace.QName NAME =
        new javax.xml.namespace.QName("http://www.w3.org/2001/XInclude", "include", "xi");

    public Include(final org.w3.www._2001.XInclude.yAA.$IncludeType copy) {
      super(copy);
    }

    public Include() {
      super();
    }

    public Include(final java.lang.String text) {
      super(text);
    }

    @java.lang.Override
    public java.lang.String text() {
      return (java.lang.String) super.text();
    }

    public void text(final java.lang.String text) {
      super.text(text);
    }

    public Include(final java.lang.Object text) {
      super(text);
    }

    @java.lang.Override
    protected org.w3.www._2001.XInclude.yAA.$IncludeType inherits() {
      return this;
    }

    @java.lang.Override
    public javax.xml.namespace.QName name() {
      return NAME;
    }

    @java.lang.Override
    public java.util.Iterator<org.w3.www._2001.XMLSchema.yAA.$AnySimpleType> attributeIterator() {
      return super.attributeIterator();
    }

    @java.lang.Override
    public java.util.Iterator<org.w3.www._2001.XMLSchema.yAA.$AnyType> elementIterator() {
      return super.elementIterator();
    }

    @java.lang.Override
    public org.jaxsb.runtime.BindingList<org.w3.www._2001.XMLSchema.yAA.$AnyType> fetchChild(
        final javax.xml.namespace.QName name) {
      return super.fetchChild(name);
    }

    @java.lang.Override
    protected org.w3c.dom.Attr marshalAttr(
        final java.lang.String name, final org.w3c.dom.Element parent)
        throws org.jaxsb.runtime.MarshalException {
      return super.marshalAttr(name, parent);
    }

    @java.lang.Override
    public org.w3c.dom.Element marshal() throws org.jaxsb.runtime.MarshalException {
      org.w3c.dom.Element root = createElementNS(name().getNamespaceURI(), name().getLocalPart());
      org.w3c.dom.Element node = marshal(root, name(), type(_$$inheritsInstance()));
      _$$marshalElements(node);
      if (org.jaxsb.runtime.BindingValidator.getSystemValidator() != null)
        org.jaxsb.runtime.BindingValidator.getSystemValidator().validateMarshal(node);
      return node;
    }

    @java.lang.Override
    protected org.w3c.dom.Element marshal(
        final org.w3c.dom.Element parent,
        final javax.xml.namespace.QName name,
        final javax.xml.namespace.QName type)
        throws org.jaxsb.runtime.MarshalException {
      final org.w3c.dom.Element node = super.marshal(parent, name, type);
      return node;
    }

    @java.lang.Override
    public org.w3.www._2001.XInclude.yAA.Include clone() {
      return (org.w3.www._2001.XInclude.yAA.Include) super.clone();
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (this == obj) return true;
      if (!(obj instanceof org.w3.www._2001.XInclude.yAA.$IncludeType)) return _$$failEquals();
      return super.equals(obj);
    }

    @java.lang.Override
    public int hashCode() {
      int hashCode = super.hashCode();
      return hashCode;
    }
  }

  @org.jaxsb.runtime.QName(
      namespaceURI = "http://www.w3.org/2001/XInclude",
      localPart = "includeType",
      prefix = "xi")
  public abstract static class $IncludeType extends org.w3.www._2001.XMLSchema.yAA.$AnySimpleType
      implements org.jaxsb.runtime.ComplexType {
    private static final javax.xml.namespace.QName NAME =
        new javax.xml.namespace.QName("http://www.w3.org/2001/XInclude", "includeType", "xi");

    protected static $IncludeType newInstance(
        final org.w3.www._2001.XInclude.yAA.$IncludeType inherits) {
      return new org.w3.www._2001.XInclude.yAA.$IncludeType() {
        @java.lang.Override
        protected org.w3.www._2001.XInclude.yAA.$IncludeType inherits() {
          return inherits;
        }
      };
    }

    private java.lang.String text = null;
    private org.jaxsb.runtime.AttributeAudit<org.w3.www._2001.XInclude.yAA.$IncludeType.Href$>
        _href$Local =
            __$$registerAttributeAudit(
                new org.jaxsb.runtime.AttributeAudit<>(
                    this,
                    null,
                    new javax.xml.namespace.QName("http://www.w3.org/2001/XInclude", "href", "xi"),
                    false,
                    false));
    private org.jaxsb.runtime.AttributeAudit<org.w3.www._2001.XInclude.yAA.$IncludeType.Parse$>
        _parse$Local =
            __$$registerAttributeAudit(
                new org.jaxsb.runtime.AttributeAudit<>(
                    this,
                    new org.w3.www._2001.XInclude.yAA.$IncludeType.Parse$(
                        org.w3.www._2001.XInclude.yAA.$IncludeType.Parse$.xml),
                    new javax.xml.namespace.QName("http://www.w3.org/2001/XInclude", "parse", "xi"),
                    false,
                    false));
    private org.jaxsb.runtime.AttributeAudit<org.w3.www._2001.XInclude.yAA.$IncludeType.Xpointer$>
        _xpointer$Local =
            __$$registerAttributeAudit(
                new org.jaxsb.runtime.AttributeAudit<>(
                    this,
                    null,
                    new javax.xml.namespace.QName(
                        "http://www.w3.org/2001/XInclude", "xpointer", "xi"),
                    false,
                    false));
    private org.jaxsb.runtime.AttributeAudit<org.w3.www._2001.XInclude.yAA.$IncludeType.Encoding$>
        _encoding$Local =
            __$$registerAttributeAudit(
                new org.jaxsb.runtime.AttributeAudit<>(
                    this,
                    null,
                    new javax.xml.namespace.QName(
                        "http://www.w3.org/2001/XInclude", "encoding", "xi"),
                    false,
                    false));
    private org.jaxsb.runtime.AttributeAudit<org.w3.www._2001.XInclude.yAA.$IncludeType.Accept$>
        _accept$Local =
            __$$registerAttributeAudit(
                new org.jaxsb.runtime.AttributeAudit<>(
                    this,
                    null,
                    new javax.xml.namespace.QName(
                        "http://www.w3.org/2001/XInclude", "accept", "xi"),
                    false,
                    false));
    private org.jaxsb.runtime.AttributeAudit<
            org.w3.www._2001.XInclude.yAA.$IncludeType.Accept$_language$>
        _accept$_language$Local =
            __$$registerAttributeAudit(
                new org.jaxsb.runtime.AttributeAudit<>(
                    this,
                    null,
                    new javax.xml.namespace.QName(
                        "http://www.w3.org/2001/XInclude", "accept-language", "xi"),
                    false,
                    false));
    private org.jaxsb.runtime.AnyAttributeAudit<org.w3.www._2001.XMLSchema.yAA.$AnySimpleType>
        anyAttribute = new org.jaxsb.runtime.AnyAttributeAudit<>(false, false);
    private org.jaxsb.runtime.ElementAudit<org.w3.www._2001.XInclude.yAA.$FallbackType>
        _xifallbackRef =
            new org.jaxsb.runtime.ElementAudit<>(
                org.w3.www._2001.XInclude.yAA.$FallbackType.class,
                this,
                null,
                new javax.xml.namespace.QName("http://www.w3.org/2001/XInclude", "fallback", "xi"),
                new javax.xml.namespace.QName(
                    "http://www.w3.org/2001/XInclude", "fallbackType", "xi"),
                true,
                false,
                0,
                2147483647);
    private org.jaxsb.runtime.ElementAudit<org.w3.www._2001.XMLSchema.yAA.$AnyType> any =
        new org.jaxsb.runtime.ElementAudit<>(
            org.w3.www._2001.XMLSchema.yAA.$AnyType.class,
            this,
            null,
            null,
            null,
            true,
            false,
            0,
            2147483647);

    public $IncludeType(final org.w3.www._2001.XInclude.yAA.$IncludeType copy) {
      super(copy);
      this._href$Local = copy._href$Local;
      this._parse$Local = copy._parse$Local;
      this._xpointer$Local = copy._xpointer$Local;
      this._encoding$Local = copy._encoding$Local;
      this._accept$Local = copy._accept$Local;
      this._accept$_language$Local = copy._accept$_language$Local;
      this.anyAttribute = copy.anyAttribute;
      this._xifallbackRef = copy._xifallbackRef;
      this.any = copy.any;
    }

    public $IncludeType(final java.lang.Object text) {
      super(text);
    }

    public $IncludeType() {
      super();
    }

    @java.lang.Override
    public java.lang.String text() {
      return text;
    }

    public void text(final java.lang.String text) {
      this.text = text;
    }

    @org.jaxsb.runtime.AttributeSpec(use = "optional")
    public void setHref$(final org.w3.www._2001.XInclude.yAA.$IncludeType.Href$ _href$Local) {
      _$$setAttribute(this._href$Local, this, _href$Local);
    }

    public void setHref$(final java.net.URI text) {
      setHref$(text == null ? null : new org.w3.www._2001.XInclude.yAA.$IncludeType.Href$(text));
    }

    public org.w3.www._2001.XInclude.yAA.$IncludeType.Href$ getHref$() {
      return _href$Local.getAttribute();
    }

    @org.jaxsb.runtime.AttributeSpec(use = "optional")
    public void setParse$(final org.w3.www._2001.XInclude.yAA.$IncludeType.Parse$ _parse$Local) {
      _$$setAttribute(this._parse$Local, this, _parse$Local);
    }

    public void setParse$(final org.w3.www._2001.XInclude.yAA.$ParseType.Enum text) {
      setParse$(text == null ? null : new org.w3.www._2001.XInclude.yAA.$IncludeType.Parse$(text));
    }

    public org.w3.www._2001.XInclude.yAA.$IncludeType.Parse$ getParse$() {
      return _parse$Local.getAttribute();
    }

    @org.jaxsb.runtime.AttributeSpec(use = "optional")
    public void setXpointer$(
        final org.w3.www._2001.XInclude.yAA.$IncludeType.Xpointer$ _xpointer$Local) {
      _$$setAttribute(this._xpointer$Local, this, _xpointer$Local);
    }

    public void setXpointer$(final java.lang.String text) {
      setXpointer$(
          text == null ? null : new org.w3.www._2001.XInclude.yAA.$IncludeType.Xpointer$(text));
    }

    public org.w3.www._2001.XInclude.yAA.$IncludeType.Xpointer$ getXpointer$() {
      return _xpointer$Local.getAttribute();
    }

    @org.jaxsb.runtime.AttributeSpec(use = "optional")
    public void setEncoding$(
        final org.w3.www._2001.XInclude.yAA.$IncludeType.Encoding$ _encoding$Local) {
      _$$setAttribute(this._encoding$Local, this, _encoding$Local);
    }

    public void setEncoding$(final java.lang.String text) {
      setEncoding$(
          text == null ? null : new org.w3.www._2001.XInclude.yAA.$IncludeType.Encoding$(text));
    }

    public org.w3.www._2001.XInclude.yAA.$IncludeType.Encoding$ getEncoding$() {
      return _encoding$Local.getAttribute();
    }

    @org.jaxsb.runtime.AttributeSpec(use = "optional")
    public void setAccept$(final org.w3.www._2001.XInclude.yAA.$IncludeType.Accept$ _accept$Local) {
      _$$setAttribute(this._accept$Local, this, _accept$Local);
    }

    public void setAccept$(final java.lang.String text) {
      setAccept$(
          text == null ? null : new org.w3.www._2001.XInclude.yAA.$IncludeType.Accept$(text));
    }

    public org.w3.www._2001.XInclude.yAA.$IncludeType.Accept$ getAccept$() {
      return _accept$Local.getAttribute();
    }

    @org.jaxsb.runtime.AttributeSpec(use = "optional")
    public void setAccept$_language$(
        final org.w3.www._2001.XInclude.yAA.$IncludeType.Accept$_language$
            _accept$_language$Local) {
      _$$setAttribute(this._accept$_language$Local, this, _accept$_language$Local);
    }

    public void setAccept$_language$(final java.lang.String text) {
      setAccept$_language$(
          text == null
              ? null
              : new org.w3.www._2001.XInclude.yAA.$IncludeType.Accept$_language$(text));
    }

    public org.w3.www._2001.XInclude.yAA.$IncludeType.Accept$_language$ getAccept$_language$() {
      return _accept$_language$Local.getAttribute();
    }

    public void addAny$(final org.w3.www._2001.XMLSchema.yAA.$AnySimpleType anyAttribute) {
      if (this.anyAttribute.getAttribute() == null)
        this.anyAttribute.setAttribute(new java.util.ArrayList<>());
      this.anyAttribute.getAttribute().add(anyAttribute);
    }

    public java.util.List<org.w3.www._2001.XMLSchema.yAA.$AnySimpleType> getAny$() {
      return anyAttribute.getAttribute();
    }

    public org.w3.www._2001.XMLSchema.yAA.$AnySimpleType getAny$(final int index) {
      final java.util.List<org.w3.www._2001.XMLSchema.yAA.$AnySimpleType> values = getAny$();
      return values != null && -1 < index && index < values.size() ? values.get(index) : null;
    }

    @org.jaxsb.runtime.ElementSpec(minOccurs = 0, maxOccurs = 2147483647)
    public org.w3.www._2001.XInclude.yAA.$FallbackType addXiFallback(
        final org.w3.www._2001.XInclude.yAA.$FallbackType _xifallbackRef) {
      _$$addElement(this._xifallbackRef, _xifallbackRef);
      return _xifallbackRef;
    }

    public org.jaxsb.runtime.BindingList<org.w3.www._2001.XInclude.yAA.$FallbackType>
        getXiFallback() {
      return _xifallbackRef.getElements();
    }

    public org.w3.www._2001.XInclude.yAA.$FallbackType getXiFallback(final int index) {
      final org.jaxsb.runtime.BindingList<org.w3.www._2001.XInclude.yAA.$FallbackType> values =
          getXiFallback();
      return values == null || index < 0 || values.size() <= index ? null : values.get(index);
    }

    public void add$Any(final org.w3.www._2001.XMLSchema.yAA.$AnyType any) {
      _$$addElement(this.any, any);
    }

    public java.util.List<org.w3.www._2001.XMLSchema.yAA.$AnyType> get$Any() {
      return any.getElements();
    }

    public org.w3.www._2001.XMLSchema.yAA.$AnyType get$Any(final int index) {
      final java.util.List<org.w3.www._2001.XMLSchema.yAA.$AnyType> values = get$Any();
      return values != null && -1 < index && index < values.size() ? values.get(index) : null;
    }

    @java.lang.Override
    protected abstract org.w3.www._2001.XInclude.yAA.$IncludeType inherits();

    @java.lang.Override
    public javax.xml.namespace.QName name() {
      return name(_$$inheritsInstance());
    }

    @java.lang.Override
    public javax.xml.namespace.QName type() {
      return NAME;
    }

    @java.lang.Override
    public java.util.Iterator<org.w3.www._2001.XMLSchema.yAA.$AnySimpleType> attributeIterator() {
      return super.attributeIterator();
    }

    @java.lang.Override
    public java.util.Iterator<org.w3.www._2001.XMLSchema.yAA.$AnyType> elementIterator() {
      return super.elementIterator();
    }

    @java.lang.Override
    public org.jaxsb.runtime.BindingList<org.w3.www._2001.XMLSchema.yAA.$AnyType> fetchChild(
        final javax.xml.namespace.QName name) {
      return super.fetchChild(name);
    }

    @java.lang.Override
    protected org.w3c.dom.Element marshal() throws org.jaxsb.runtime.MarshalException {
      org.w3c.dom.Element root = createElementNS(name().getNamespaceURI(), name().getLocalPart());
      org.w3c.dom.Element node = marshal(root, name(), type(_$$inheritsInstance()));
      _$$marshalElements(node);
      if (org.jaxsb.runtime.BindingValidator.getSystemValidator() != null)
        org.jaxsb.runtime.BindingValidator.getSystemValidator().validateMarshal(node);
      return node;
    }

    @java.lang.Override
    protected org.w3c.dom.Element marshal(
        final org.w3c.dom.Element parent,
        final javax.xml.namespace.QName name,
        final javax.xml.namespace.QName type)
        throws org.jaxsb.runtime.MarshalException {
      org.w3c.dom.Element node = super.marshal(parent, name, type);
      _href$Local.marshal(node);
      _parse$Local.marshal(node);
      _xpointer$Local.marshal(node);
      _encoding$Local.marshal(node);
      _accept$Local.marshal(node);
      _accept$_language$Local.marshal(node);
      anyAttribute.marshal(node);
      return node;
    }

    @java.lang.Override
    protected boolean parseAttribute(final org.w3c.dom.Attr attribute) {
      if (attribute == null || XMLNS.getLocalPart().equals(attribute.getPrefix())) {
        return true;
      }
      if (attribute.getNamespaceURI() == null && "href".equals(attribute.getLocalName())) {
        return _$$setAttribute(
            this._href$Local,
            this,
            (org.w3.www._2001.XInclude.yAA.$IncludeType.Href$)
                org.jaxsb.runtime.Binding._$$parseAttr(
                    org.w3.www._2001.XInclude.yAA.$IncludeType.Href$.class,
                    attribute.getOwnerElement(),
                    attribute));
      }
      if (attribute.getNamespaceURI() == null && "parse".equals(attribute.getLocalName())) {
        return _$$setAttribute(
            this._parse$Local,
            this,
            (org.w3.www._2001.XInclude.yAA.$IncludeType.Parse$)
                org.jaxsb.runtime.Binding._$$parseAttr(
                    org.w3.www._2001.XInclude.yAA.$IncludeType.Parse$.class,
                    attribute.getOwnerElement(),
                    attribute));
      }
      if (attribute.getNamespaceURI() == null && "xpointer".equals(attribute.getLocalName())) {
        return _$$setAttribute(
            this._xpointer$Local,
            this,
            (org.w3.www._2001.XInclude.yAA.$IncludeType.Xpointer$)
                org.jaxsb.runtime.Binding._$$parseAttr(
                    org.w3.www._2001.XInclude.yAA.$IncludeType.Xpointer$.class,
                    attribute.getOwnerElement(),
                    attribute));
      }
      if (attribute.getNamespaceURI() == null && "encoding".equals(attribute.getLocalName())) {
        return _$$setAttribute(
            this._encoding$Local,
            this,
            (org.w3.www._2001.XInclude.yAA.$IncludeType.Encoding$)
                org.jaxsb.runtime.Binding._$$parseAttr(
                    org.w3.www._2001.XInclude.yAA.$IncludeType.Encoding$.class,
                    attribute.getOwnerElement(),
                    attribute));
      }
      if (attribute.getNamespaceURI() == null && "accept".equals(attribute.getLocalName())) {
        return _$$setAttribute(
            this._accept$Local,
            this,
            (org.w3.www._2001.XInclude.yAA.$IncludeType.Accept$)
                org.jaxsb.runtime.Binding._$$parseAttr(
                    org.w3.www._2001.XInclude.yAA.$IncludeType.Accept$.class,
                    attribute.getOwnerElement(),
                    attribute));
      }
      if (attribute.getNamespaceURI() == null
          && "accept-language".equals(attribute.getLocalName())) {
        return _$$setAttribute(
            this._accept$_language$Local,
            this,
            (org.w3.www._2001.XInclude.yAA.$IncludeType.Accept$_language$)
                org.jaxsb.runtime.Binding._$$parseAttr(
                    org.w3.www._2001.XInclude.yAA.$IncludeType.Accept$_language$.class,
                    attribute.getOwnerElement(),
                    attribute));
      }
      return super.parseAttribute(attribute);
    }

    @java.lang.Override
    protected void parseAnyAttribute(final org.w3c.dom.Attr attribute) {
      if (this.anyAttribute.getAttribute() == null)
        this.anyAttribute.setAttribute(new java.util.ArrayList<>());
      this.anyAttribute
          .getAttribute()
          .add(
              org.w3.www._2001.XMLSchema.yAA.$AnySimpleType._$$parseAnyAttr(
                  (org.w3c.dom.Element) attribute.getParentNode(), attribute));
    }

    @java.lang.Override
    protected boolean parseElement(final org.w3c.dom.Element element)
        throws org.openjax.xml.api.ValidationException {
      if ("http://www.w3.org/2001/XInclude".equals(element.getNamespaceURI())
          && "fallback".equals(element.getLocalName())) {
        return _$$addElement(
            this._xifallbackRef,
            (org.w3.www._2001.XInclude.yAA.$FallbackType)
                org.jaxsb.runtime.Binding.parse(
                    element, org.w3.www._2001.XInclude.yAA.Fallback.class));
      }
      if (org.jaxsb.runtime.Binding._$$iSsubstitutionGroup(
          new javax.xml.namespace.QName(element.getNamespaceURI(), element.getLocalName()),
          "http://www.w3.org/2001/XInclude",
          "fallback")) {
        return _$$addElement(
            this._xifallbackRef,
            (org.w3.www._2001.XInclude.yAA.$FallbackType) org.jaxsb.runtime.Binding.parse(element));
      }
      return super.parseElement(element);
    }

    @java.lang.Override
    protected void parseAny(final org.w3c.dom.Element element)
        throws org.openjax.xml.api.ValidationException {
      if (element.getNodeType() != org.w3c.dom.Node.ELEMENT_NODE) return;
      _$$addElement(this.any, org.jaxsb.runtime.Bindings.parse((org.w3c.dom.Element) element));
    }

    @java.lang.Override
    public org.w3.www._2001.XInclude.yAA.$IncludeType clone() {
      final org.w3.www._2001.XInclude.yAA.$IncludeType clone =
          (org.w3.www._2001.XInclude.yAA.$IncludeType) super.clone();
      clone._href$Local = _href$Local.clone(clone);
      clone._parse$Local = _parse$Local.clone(clone);
      clone._xpointer$Local = _xpointer$Local.clone(clone);
      clone._encoding$Local = _encoding$Local.clone(clone);
      clone._accept$Local = _accept$Local.clone(clone);
      clone._accept$_language$Local = _accept$_language$Local.clone(clone);
      clone.anyAttribute = anyAttribute.clone(clone);
      clone._xifallbackRef = _xifallbackRef == null ? null : clone.getAudit(_xifallbackRef);
      clone.any = any == null ? null : clone.getAudit(any);
      return clone;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (this == obj) return true;
      if (!(obj instanceof org.w3.www._2001.XInclude.yAA.$IncludeType)) return _$$failEquals();
      final org.w3.www._2001.XInclude.yAA.$IncludeType that =
          (org.w3.www._2001.XInclude.yAA.$IncludeType) obj;
      if (_href$Local != null ? !_href$Local.equals(that._href$Local) : that._href$Local != null)
        return _$$failEquals();
      if (_parse$Local != null
          ? !_parse$Local.equals(that._parse$Local)
          : that._parse$Local != null) return _$$failEquals();
      if (_xpointer$Local != null
          ? !_xpointer$Local.equals(that._xpointer$Local)
          : that._xpointer$Local != null) return _$$failEquals();
      if (_encoding$Local != null
          ? !_encoding$Local.equals(that._encoding$Local)
          : that._encoding$Local != null) return _$$failEquals();
      if (_accept$Local != null
          ? !_accept$Local.equals(that._accept$Local)
          : that._accept$Local != null) return _$$failEquals();
      if (_accept$_language$Local != null
          ? !_accept$_language$Local.equals(that._accept$_language$Local)
          : that._accept$_language$Local != null) return _$$failEquals();
      if (anyAttribute != null
          ? !anyAttribute.equals(that.anyAttribute)
          : that.anyAttribute != null) return _$$failEquals();
      if (_xifallbackRef != null
          ? !_xifallbackRef.equals(that._xifallbackRef)
          : that._xifallbackRef != null) return _$$failEquals();
      if (any != null ? !any.equals(that.any) : that.any != null) return _$$failEquals();
      return super.equals(obj);
    }

    @java.lang.Override
    public int hashCode() {
      int hashCode = super.hashCode();
      if (text != null) hashCode = 31 * hashCode + text.hashCode();
      if (_href$Local != null) hashCode = 31 * hashCode + _href$Local.hashCode();
      if (_parse$Local != null) hashCode = 31 * hashCode + _parse$Local.hashCode();
      if (_xpointer$Local != null) hashCode = 31 * hashCode + _xpointer$Local.hashCode();
      if (_encoding$Local != null) hashCode = 31 * hashCode + _encoding$Local.hashCode();
      if (_accept$Local != null) hashCode = 31 * hashCode + _accept$Local.hashCode();
      if (_accept$_language$Local != null)
        hashCode = 31 * hashCode + _accept$_language$Local.hashCode();
      if (anyAttribute != null) hashCode = 31 * hashCode + anyAttribute.hashCode();
      if (_xifallbackRef != null) hashCode = 31 * hashCode + _xifallbackRef.hashCode();
      if (any != null) hashCode = 31 * hashCode + any.hashCode();
      return hashCode;
    }

    @org.jaxsb.runtime.QName(
        namespaceURI = "http://www.w3.org/2001/XInclude",
        localPart = "href",
        prefix = "xi")
    public static class Href$ extends org.w3.www._2001.XMLSchema.yAA.$AnyURI
        implements org.jaxsb.runtime.Attribute {
      private static final javax.xml.namespace.QName NAME =
          new javax.xml.namespace.QName("http://www.w3.org/2001/XInclude", "href", "xi");

      public Href$(final org.w3.www._2001.XMLSchema.yAA.$AnyURI copy) {
        super(copy);
      }

      public Href$(final java.net.URI text) {
        super(text);
      }

      public Href$() {
        super();
      }

      @java.lang.Override
      protected org.w3.www._2001.XMLSchema.yAA.$AnyURI inherits() {
        return this;
      }

      @java.lang.Override
      public javax.xml.namespace.QName name() {
        return NAME;
      }

      @java.lang.Override
      public java.net.URI text() {
        return (java.net.URI) super.text();
      }

      @java.lang.Override
      public org.w3.www._2001.XMLSchema.yAA.$AnyURI clone() {
        return (org.w3.www._2001.XInclude.yAA.$IncludeType.Href$) super.clone();
      }
    }

    @org.jaxsb.runtime.QName(
        namespaceURI = "http://www.w3.org/2001/XInclude",
        localPart = "parse",
        prefix = "xi")
    public static class Parse$ extends org.w3.www._2001.XInclude.yAA.$ParseType
        implements org.jaxsb.runtime.Attribute {
      private static final javax.xml.namespace.QName NAME =
          new javax.xml.namespace.QName("http://www.w3.org/2001/XInclude", "parse", "xi");

      public static class Enum extends org.w3.www._2001.XInclude.yAA.$ParseType.Enum {
        protected static java.util.Map<
                java.lang.String, org.w3.www._2001.XInclude.yAA.$ParseType.Enum>
            values() {
          return org.w3.www._2001.XInclude.yAA.$ParseType.Enum.values();
        };

        @java.lang.Override
        public int ordinal() {
          return super.ordinal();
        }

        protected Enum(final java.lang.String text) {
          super(text);
        }
      }

      @java.lang.Override
      public int ordinal() {
        final org.w3.www._2001.XInclude.yAA.$ParseType.Enum enm = Enum.values().get(text());
        return enm != null ? enm.ordinal() : -1;
      }

      public Parse$(final org.w3.www._2001.XInclude.yAA.$ParseType.Enum enm) {
        super(enm);
      }

      public Parse$(final org.w3.www._2001.XInclude.yAA.$IncludeType.Parse$ copy) {
        super(copy);
      }

      protected Parse$(final java.lang.String text) {
        super(text);
      }

      protected Parse$() {
        super();
      }

      @java.lang.Override
      protected org.w3.www._2001.XInclude.yAA.$ParseType inherits() {
        return this;
      }

      @java.lang.Override
      public javax.xml.namespace.QName name() {
        return NAME;
      }

      @java.lang.Override
      public java.lang.String text() {
        return (java.lang.String) super.text();
      }

      @java.lang.Override
      public org.w3.www._2001.XInclude.yAA.$ParseType clone() {
        return (org.w3.www._2001.XInclude.yAA.$IncludeType.Parse$) super.clone();
      }
    }

    @org.jaxsb.runtime.QName(
        namespaceURI = "http://www.w3.org/2001/XInclude",
        localPart = "xpointer",
        prefix = "xi")
    public static class Xpointer$ extends org.w3.www._2001.XMLSchema.yAA.$String
        implements org.jaxsb.runtime.Attribute {
      private static final javax.xml.namespace.QName NAME =
          new javax.xml.namespace.QName("http://www.w3.org/2001/XInclude", "xpointer", "xi");

      public Xpointer$(final org.w3.www._2001.XMLSchema.yAA.$String copy) {
        super(copy);
      }

      public Xpointer$(final java.lang.String text) {
        super(text);
      }

      public Xpointer$() {
        super();
      }

      @java.lang.Override
      protected org.w3.www._2001.XMLSchema.yAA.$String inherits() {
        return this;
      }

      @java.lang.Override
      public javax.xml.namespace.QName name() {
        return NAME;
      }

      @java.lang.Override
      public java.lang.String text() {
        return (java.lang.String) super.text();
      }

      @java.lang.Override
      public org.w3.www._2001.XMLSchema.yAA.$String clone() {
        return (org.w3.www._2001.XInclude.yAA.$IncludeType.Xpointer$) super.clone();
      }
    }

    @org.jaxsb.runtime.QName(
        namespaceURI = "http://www.w3.org/2001/XInclude",
        localPart = "encoding",
        prefix = "xi")
    public static class Encoding$ extends org.w3.www._2001.XMLSchema.yAA.$String
        implements org.jaxsb.runtime.Attribute {
      private static final javax.xml.namespace.QName NAME =
          new javax.xml.namespace.QName("http://www.w3.org/2001/XInclude", "encoding", "xi");

      public Encoding$(final org.w3.www._2001.XMLSchema.yAA.$String copy) {
        super(copy);
      }

      public Encoding$(final java.lang.String text) {
        super(text);
      }

      public Encoding$() {
        super();
      }

      @java.lang.Override
      protected org.w3.www._2001.XMLSchema.yAA.$String inherits() {
        return this;
      }

      @java.lang.Override
      public javax.xml.namespace.QName name() {
        return NAME;
      }

      @java.lang.Override
      public java.lang.String text() {
        return (java.lang.String) super.text();
      }

      @java.lang.Override
      public org.w3.www._2001.XMLSchema.yAA.$String clone() {
        return (org.w3.www._2001.XInclude.yAA.$IncludeType.Encoding$) super.clone();
      }
    }

    @org.jaxsb.runtime.QName(
        namespaceURI = "http://www.w3.org/2001/XInclude",
        localPart = "accept",
        prefix = "xi")
    public static class Accept$ extends org.w3.www._2001.XMLSchema.yAA.$String
        implements org.jaxsb.runtime.Attribute {
      private static final javax.xml.namespace.QName NAME =
          new javax.xml.namespace.QName("http://www.w3.org/2001/XInclude", "accept", "xi");

      public Accept$(final org.w3.www._2001.XMLSchema.yAA.$String copy) {
        super(copy);
      }

      public Accept$(final java.lang.String text) {
        super(text);
      }

      public Accept$() {
        super();
      }

      @java.lang.Override
      protected org.w3.www._2001.XMLSchema.yAA.$String inherits() {
        return this;
      }

      @java.lang.Override
      public javax.xml.namespace.QName name() {
        return NAME;
      }

      @java.lang.Override
      public java.lang.String text() {
        return (java.lang.String) super.text();
      }

      @java.lang.Override
      public org.w3.www._2001.XMLSchema.yAA.$String clone() {
        return (org.w3.www._2001.XInclude.yAA.$IncludeType.Accept$) super.clone();
      }
    }

    @org.jaxsb.runtime.QName(
        namespaceURI = "http://www.w3.org/2001/XInclude",
        localPart = "accept-language",
        prefix = "xi")
    public static class Accept$_language$ extends org.w3.www._2001.XMLSchema.yAA.$String
        implements org.jaxsb.runtime.Attribute {
      private static final javax.xml.namespace.QName NAME =
          new javax.xml.namespace.QName("http://www.w3.org/2001/XInclude", "accept-language", "xi");

      public Accept$_language$(final org.w3.www._2001.XMLSchema.yAA.$String copy) {
        super(copy);
      }

      public Accept$_language$(final java.lang.String text) {
        super(text);
      }

      public Accept$_language$() {
        super();
      }

      @java.lang.Override
      protected org.w3.www._2001.XMLSchema.yAA.$String inherits() {
        return this;
      }

      @java.lang.Override
      public javax.xml.namespace.QName name() {
        return NAME;
      }

      @java.lang.Override
      public java.lang.String text() {
        return (java.lang.String) super.text();
      }

      @java.lang.Override
      public org.w3.www._2001.XMLSchema.yAA.$String clone() {
        return (org.w3.www._2001.XInclude.yAA.$IncludeType.Accept$_language$) super.clone();
      }
    }
  }

  @org.jaxsb.runtime.QName(
      namespaceURI = "http://www.w3.org/2001/XInclude",
      localPart = "parseType",
      prefix = "xi")
  public abstract static class $ParseType extends org.w3.www._2001.XMLSchema.yAA.$Token
      implements org.jaxsb.runtime.SimpleType {
    private static final javax.xml.namespace.QName NAME =
        new javax.xml.namespace.QName("http://www.w3.org/2001/XInclude", "parseType", "xi");

    protected static $ParseType newInstance(
        final org.w3.www._2001.XInclude.yAA.$ParseType inherits) {
      return new org.w3.www._2001.XInclude.yAA.$ParseType() {
        @java.lang.Override
        protected org.w3.www._2001.XInclude.yAA.$ParseType inherits() {
          return inherits;
        }
      };
    }

    public $ParseType(org.w3.www._2001.XInclude.yAA.$ParseType copy) {
      super(copy);
    }

    public static final Enum xml = new Enum("xml");
    public static final Enum text = new Enum("text");

    public static class Enum implements org.jaxsb.runtime.Enum<java.lang.String> {
      protected static final java.util.Map<java.lang.String, Enum> values =
          new java.util.HashMap<>();

      protected static java.util.Map<java.lang.String, Enum> values() {
        return values;
      };

      public static Enum valueOf(final java.lang.String s) {
        return values.get(s);
      };

      protected final java.lang.String text;
      protected final int ordinal;

      @java.lang.Override
      public int ordinal() {
        return ordinal;
      }

      protected Enum(final java.lang.String text) {
        this.text = text;
        this.ordinal = values.size();
        values.put(text, this);
      }

      @java.lang.Override
      public java.lang.String text() {
        return text;
      }
    }

    public int ordinal() {
      final Enum enm = Enum.values().get(text());
      return enm != null ? enm.ordinal() : -1;
    }

    public $ParseType(final Enum enm) {
      super(enm.text());
    }

    protected $ParseType(final java.lang.String text) {
      super(text);
    }

    protected $ParseType() {
      super();
    }

    @java.lang.Override
    public java.lang.String text() {
      return (java.lang.String) super.text();
    }

    public void text(final Enum enm) {
      super.text(enm.text);
    }

    @java.lang.Override
    protected abstract org.w3.www._2001.XInclude.yAA.$ParseType inherits();

    @java.lang.Override
    public javax.xml.namespace.QName name() {
      return name(_$$inheritsInstance());
    }

    @java.lang.Override
    public javax.xml.namespace.QName type() {
      return NAME;
    }

    @java.lang.Override
    protected org.w3c.dom.Attr marshalAttr(
        final java.lang.String name, final org.w3c.dom.Element parent)
        throws org.jaxsb.runtime.MarshalException {
      return super.marshalAttr(name, parent);
    }

    @java.lang.Override
    protected org.w3c.dom.Element marshal() throws org.jaxsb.runtime.MarshalException {
      org.w3c.dom.Element root = createElementNS(name().getNamespaceURI(), name().getLocalPart());
      return marshal(root, name(), type(_$$inheritsInstance()));
    }

    @java.lang.Override
    protected org.w3c.dom.Element marshal(
        final org.w3c.dom.Element parent,
        final javax.xml.namespace.QName name,
        final javax.xml.namespace.QName type)
        throws org.jaxsb.runtime.MarshalException {
      return super.marshal(parent, name, type);
    }

    @java.lang.Override
    public org.w3.www._2001.XInclude.yAA.$ParseType clone() {
      return (org.w3.www._2001.XInclude.yAA.$ParseType) super.clone();
    }
  }

  @org.jaxsb.runtime.QName(
      namespaceURI = "http://www.w3.org/2001/XInclude",
      localPart = "fallback",
      prefix = "xi")
  public static class Fallback extends org.w3.www._2001.XInclude.yAA.$FallbackType
      implements org.jaxsb.runtime.ComplexType, org.jaxsb.runtime.Element {
    private static final javax.xml.namespace.QName NAME =
        new javax.xml.namespace.QName("http://www.w3.org/2001/XInclude", "fallback", "xi");

    public Fallback(final org.w3.www._2001.XInclude.yAA.$FallbackType copy) {
      super(copy);
    }

    public Fallback() {
      super();
    }

    public Fallback(final java.lang.String text) {
      super(text);
    }

    @java.lang.Override
    public java.lang.String text() {
      return (java.lang.String) super.text();
    }

    public void text(final java.lang.String text) {
      super.text(text);
    }

    public Fallback(final java.lang.Object text) {
      super(text);
    }

    @java.lang.Override
    protected org.w3.www._2001.XInclude.yAA.$FallbackType inherits() {
      return this;
    }

    @java.lang.Override
    public javax.xml.namespace.QName name() {
      return NAME;
    }

    @java.lang.Override
    public java.util.Iterator<org.w3.www._2001.XMLSchema.yAA.$AnySimpleType> attributeIterator() {
      return super.attributeIterator();
    }

    @java.lang.Override
    public java.util.Iterator<org.w3.www._2001.XMLSchema.yAA.$AnyType> elementIterator() {
      return super.elementIterator();
    }

    @java.lang.Override
    public org.jaxsb.runtime.BindingList<org.w3.www._2001.XMLSchema.yAA.$AnyType> fetchChild(
        final javax.xml.namespace.QName name) {
      return super.fetchChild(name);
    }

    @java.lang.Override
    protected org.w3c.dom.Attr marshalAttr(
        final java.lang.String name, final org.w3c.dom.Element parent)
        throws org.jaxsb.runtime.MarshalException {
      return super.marshalAttr(name, parent);
    }

    @java.lang.Override
    public org.w3c.dom.Element marshal() throws org.jaxsb.runtime.MarshalException {
      org.w3c.dom.Element root = createElementNS(name().getNamespaceURI(), name().getLocalPart());
      org.w3c.dom.Element node = marshal(root, name(), type(_$$inheritsInstance()));
      _$$marshalElements(node);
      if (org.jaxsb.runtime.BindingValidator.getSystemValidator() != null)
        org.jaxsb.runtime.BindingValidator.getSystemValidator().validateMarshal(node);
      return node;
    }

    @java.lang.Override
    protected org.w3c.dom.Element marshal(
        final org.w3c.dom.Element parent,
        final javax.xml.namespace.QName name,
        final javax.xml.namespace.QName type)
        throws org.jaxsb.runtime.MarshalException {
      final org.w3c.dom.Element node = super.marshal(parent, name, type);
      return node;
    }

    @java.lang.Override
    public org.w3.www._2001.XInclude.yAA.Fallback clone() {
      return (org.w3.www._2001.XInclude.yAA.Fallback) super.clone();
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (this == obj) return true;
      if (!(obj instanceof org.w3.www._2001.XInclude.yAA.$FallbackType)) return _$$failEquals();
      return super.equals(obj);
    }

    @java.lang.Override
    public int hashCode() {
      int hashCode = super.hashCode();
      return hashCode;
    }
  }

  @org.jaxsb.runtime.QName(
      namespaceURI = "http://www.w3.org/2001/XInclude",
      localPart = "fallbackType",
      prefix = "xi")
  public abstract static class $FallbackType extends org.w3.www._2001.XMLSchema.yAA.$AnySimpleType
      implements org.jaxsb.runtime.ComplexType {
    private static final javax.xml.namespace.QName NAME =
        new javax.xml.namespace.QName("http://www.w3.org/2001/XInclude", "fallbackType", "xi");

    protected static $FallbackType newInstance(
        final org.w3.www._2001.XInclude.yAA.$FallbackType inherits) {
      return new org.w3.www._2001.XInclude.yAA.$FallbackType() {
        @java.lang.Override
        protected org.w3.www._2001.XInclude.yAA.$FallbackType inherits() {
          return inherits;
        }
      };
    }

    private java.lang.String text = null;
    private org.jaxsb.runtime.AnyAttributeAudit<org.w3.www._2001.XMLSchema.yAA.$AnySimpleType>
        anyAttribute = new org.jaxsb.runtime.AnyAttributeAudit<>(false, false);
    private org.jaxsb.runtime.ElementAudit<org.w3.www._2001.XInclude.yAA.$IncludeType>
        _xiincludeRef =
            new org.jaxsb.runtime.ElementAudit<>(
                org.w3.www._2001.XInclude.yAA.$IncludeType.class,
                this,
                null,
                new javax.xml.namespace.QName("http://www.w3.org/2001/XInclude", "include", "xi"),
                new javax.xml.namespace.QName(
                    "http://www.w3.org/2001/XInclude", "includeType", "xi"),
                true,
                false,
                0,
                2147483647);
    private org.jaxsb.runtime.ElementAudit<org.w3.www._2001.XMLSchema.yAA.$AnyType> any =
        new org.jaxsb.runtime.ElementAudit<>(
            org.w3.www._2001.XMLSchema.yAA.$AnyType.class,
            this,
            null,
            null,
            null,
            true,
            false,
            0,
            2147483647);

    public $FallbackType(final org.w3.www._2001.XInclude.yAA.$FallbackType copy) {
      super(copy);
      this.anyAttribute = copy.anyAttribute;
      this._xiincludeRef = copy._xiincludeRef;
      this.any = copy.any;
    }

    public $FallbackType(final java.lang.Object text) {
      super(text);
    }

    public $FallbackType() {
      super();
    }

    @java.lang.Override
    public java.lang.String text() {
      return text;
    }

    public void text(final java.lang.String text) {
      this.text = text;
    }

    public void addAny$(final org.w3.www._2001.XMLSchema.yAA.$AnySimpleType anyAttribute) {
      if (this.anyAttribute.getAttribute() == null)
        this.anyAttribute.setAttribute(new java.util.ArrayList<>());
      this.anyAttribute.getAttribute().add(anyAttribute);
    }

    public java.util.List<org.w3.www._2001.XMLSchema.yAA.$AnySimpleType> getAny$() {
      return anyAttribute.getAttribute();
    }

    public org.w3.www._2001.XMLSchema.yAA.$AnySimpleType getAny$(final int index) {
      final java.util.List<org.w3.www._2001.XMLSchema.yAA.$AnySimpleType> values = getAny$();
      return values != null && -1 < index && index < values.size() ? values.get(index) : null;
    }

    @org.jaxsb.runtime.ElementSpec(minOccurs = 0, maxOccurs = 2147483647)
    public org.w3.www._2001.XInclude.yAA.$IncludeType addXiInclude(
        final org.w3.www._2001.XInclude.yAA.$IncludeType _xiincludeRef) {
      _$$addElement(this._xiincludeRef, _xiincludeRef);
      return _xiincludeRef;
    }

    public org.jaxsb.runtime.BindingList<org.w3.www._2001.XInclude.yAA.$IncludeType>
        getXiInclude() {
      return _xiincludeRef.getElements();
    }

    public org.w3.www._2001.XInclude.yAA.$IncludeType getXiInclude(final int index) {
      final org.jaxsb.runtime.BindingList<org.w3.www._2001.XInclude.yAA.$IncludeType> values =
          getXiInclude();
      return values == null || index < 0 || values.size() <= index ? null : values.get(index);
    }

    public void add$Any(final org.w3.www._2001.XMLSchema.yAA.$AnyType any) {
      _$$addElement(this.any, any);
    }

    public java.util.List<org.w3.www._2001.XMLSchema.yAA.$AnyType> get$Any() {
      return any.getElements();
    }

    public org.w3.www._2001.XMLSchema.yAA.$AnyType get$Any(final int index) {
      final java.util.List<org.w3.www._2001.XMLSchema.yAA.$AnyType> values = get$Any();
      return values != null && -1 < index && index < values.size() ? values.get(index) : null;
    }

    @java.lang.Override
    protected abstract org.w3.www._2001.XInclude.yAA.$FallbackType inherits();

    @java.lang.Override
    public javax.xml.namespace.QName name() {
      return name(_$$inheritsInstance());
    }

    @java.lang.Override
    public javax.xml.namespace.QName type() {
      return NAME;
    }

    @java.lang.Override
    public java.util.Iterator<org.w3.www._2001.XMLSchema.yAA.$AnySimpleType> attributeIterator() {
      return super.attributeIterator();
    }

    @java.lang.Override
    public java.util.Iterator<org.w3.www._2001.XMLSchema.yAA.$AnyType> elementIterator() {
      return super.elementIterator();
    }

    @java.lang.Override
    public org.jaxsb.runtime.BindingList<org.w3.www._2001.XMLSchema.yAA.$AnyType> fetchChild(
        final javax.xml.namespace.QName name) {
      return super.fetchChild(name);
    }

    @java.lang.Override
    protected org.w3c.dom.Element marshal() throws org.jaxsb.runtime.MarshalException {
      org.w3c.dom.Element root = createElementNS(name().getNamespaceURI(), name().getLocalPart());
      org.w3c.dom.Element node = marshal(root, name(), type(_$$inheritsInstance()));
      _$$marshalElements(node);
      if (org.jaxsb.runtime.BindingValidator.getSystemValidator() != null)
        org.jaxsb.runtime.BindingValidator.getSystemValidator().validateMarshal(node);
      return node;
    }

    @java.lang.Override
    protected org.w3c.dom.Element marshal(
        final org.w3c.dom.Element parent,
        final javax.xml.namespace.QName name,
        final javax.xml.namespace.QName type)
        throws org.jaxsb.runtime.MarshalException {
      org.w3c.dom.Element node = super.marshal(parent, name, type);
      anyAttribute.marshal(node);
      return node;
    }

    @java.lang.Override
    protected boolean parseAttribute(final org.w3c.dom.Attr attribute) {
      if (attribute == null || XMLNS.getLocalPart().equals(attribute.getPrefix())) {
        return true;
      }
      return super.parseAttribute(attribute);
    }

    @java.lang.Override
    protected void parseAnyAttribute(final org.w3c.dom.Attr attribute) {
      if (this.anyAttribute.getAttribute() == null)
        this.anyAttribute.setAttribute(new java.util.ArrayList<>());
      this.anyAttribute
          .getAttribute()
          .add(
              org.w3.www._2001.XMLSchema.yAA.$AnySimpleType._$$parseAnyAttr(
                  (org.w3c.dom.Element) attribute.getParentNode(), attribute));
    }

    @java.lang.Override
    protected boolean parseElement(final org.w3c.dom.Element element)
        throws org.openjax.xml.api.ValidationException {
      if ("http://www.w3.org/2001/XInclude".equals(element.getNamespaceURI())
          && "include".equals(element.getLocalName())) {
        return _$$addElement(
            this._xiincludeRef,
            (org.w3.www._2001.XInclude.yAA.$IncludeType)
                org.jaxsb.runtime.Binding.parse(
                    element, org.w3.www._2001.XInclude.yAA.Include.class));
      }
      if (org.jaxsb.runtime.Binding._$$iSsubstitutionGroup(
          new javax.xml.namespace.QName(element.getNamespaceURI(), element.getLocalName()),
          "http://www.w3.org/2001/XInclude",
          "include")) {
        return _$$addElement(
            this._xiincludeRef,
            (org.w3.www._2001.XInclude.yAA.$IncludeType) org.jaxsb.runtime.Binding.parse(element));
      }
      return super.parseElement(element);
    }

    @java.lang.Override
    protected void parseAny(final org.w3c.dom.Element element)
        throws org.openjax.xml.api.ValidationException {
      if (element.getNodeType() != org.w3c.dom.Node.ELEMENT_NODE) return;
      _$$addElement(this.any, org.jaxsb.runtime.Bindings.parse((org.w3c.dom.Element) element));
    }

    @java.lang.Override
    public org.w3.www._2001.XInclude.yAA.$FallbackType clone() {
      final org.w3.www._2001.XInclude.yAA.$FallbackType clone =
          (org.w3.www._2001.XInclude.yAA.$FallbackType) super.clone();
      clone.anyAttribute = anyAttribute.clone(clone);
      clone._xiincludeRef = _xiincludeRef == null ? null : clone.getAudit(_xiincludeRef);
      clone.any = any == null ? null : clone.getAudit(any);
      return clone;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (this == obj) return true;
      if (!(obj instanceof org.w3.www._2001.XInclude.yAA.$FallbackType)) return _$$failEquals();
      final org.w3.www._2001.XInclude.yAA.$FallbackType that =
          (org.w3.www._2001.XInclude.yAA.$FallbackType) obj;
      if (anyAttribute != null
          ? !anyAttribute.equals(that.anyAttribute)
          : that.anyAttribute != null) return _$$failEquals();
      if (_xiincludeRef != null
          ? !_xiincludeRef.equals(that._xiincludeRef)
          : that._xiincludeRef != null) return _$$failEquals();
      if (any != null ? !any.equals(that.any) : that.any != null) return _$$failEquals();
      return super.equals(obj);
    }

    @java.lang.Override
    public int hashCode() {
      int hashCode = super.hashCode();
      if (text != null) hashCode = 31 * hashCode + text.hashCode();
      if (anyAttribute != null) hashCode = 31 * hashCode + anyAttribute.hashCode();
      if (_xiincludeRef != null) hashCode = 31 * hashCode + _xiincludeRef.hashCode();
      if (any != null) hashCode = 31 * hashCode + any.hashCode();
      return hashCode;
    }
  }
}
